### ISSUE TITLE
Konge til tom kolonne

### ISSUE THREAD

**Issue by ArmandasRokas** [emilnt1/SolitareImageRecognition#1]

**Comment by emilnt1** [comment]
Hvis der ikke er flere træk at lave, og der er 2 tomme kolonner, bliver rækken med kongen i rykket frem og tilbage mellem de to kollonner.

**Comment by ArmandasRokas** [comment]
Mulig løsning:

- statefulBoard har styr på hvor mange 
- cardLeftColumns = [0,1,2,3,4,5,6], men i koden kender vi ikke hvornår vender vi kortene. 
-

**Comment by emilnt1** [comment]
Kongerne forbliver nu på den kollonne de er rykket til. Løst
