### ISSUE TITLE
Make draw

### ISSUE THREAD

**Issue by ArmandasRokas** [emilnt1/SolitareImageRecognition#5]
- Skal sige "Make draw", hvis der ikke nogen andre trak, der er muligt
- Som højest prioritet,  skal bede om at "Make draw",  når der er 3 kort tilbage i Deck og Draw Pile i alt. 
- Hvis der er mindre en 3 kort i Deck og Draw Pile i alt, så skal det ikke lave flere "Make draw". Dvs. hvis der ikke nogen andre trak eksistere, skal det så bare sige "No moves available"

**Comment by emilnt1** [comment]
Virker som den skal
