### ISSUE TITLE
Priority to see hidden cards.

### ISSUE THREAD

**Issue by Machnuud** [emilnt1/SolitareImageRecognition#9]
At the moment the ai makes moves from left to right. We had two black 10's and one was in the bottom of its column and the other had hidden cards under it. It chose not to reveal the hidden cards which was a losing move.

**Comment by ArmandasRokas** [comment]
Ready for test

**Comment by Machnuud** [comment]
Still not fixed now it just crashes instead.

**Comment by Machnuud** [comment]
Hurray now it works
